# Pitagoras


In [4]:
import math

In [5]:
def pit(a, b):
    return math.sqrt(a**2 + b**2)

In [6]:
pit(5,6)

7.810249675906654

In [7]:
ls

Untitled.ipynb  exercise.py


In [8]:
conda install jupyterthemes

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - jupyterthemes

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



Note: you may need to restart the kernel to use updated packages.


In [9]:
pip install jupyterthemes


     |████████████████████████████████| 7.0 MB 3.5 MB/s eta 0:00:01
     |████████████████████████████████| 46 kB 4.6 MB/s eta 0:00:01
     |████████████████████████████████| 12.4 MB 3.4 MB/s eta 0:00:01
     |████████████████████████████████| 49 kB 4.4 MB/s eta 0:00:01
     |████████████████████████████████| 15.1 MB 3.4 MB/s eta 0:00:01
     |████████████████████████████████| 67 kB 3.9 MB/s eta 0:00:01
     |████████████████████████████████| 60 kB 4.3 MB/s eta 0:00:01


Note: you may need to restart the kernel to use updated packages.


In [1]:
jt -t chesterish


SyntaxError: invalid syntax (<ipython-input-1-de2e746ade80>, line 1)

In [2]:
jt -t chesterish


SyntaxError: invalid syntax (<ipython-input-2-de2e746ade80>, line 1)

In [1]:
!pip3 install numpy

The directory '/Users/micromegas/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/micromegas/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    100% |████████████████████████████████| 15.1MB 2.2MB/s ta 0:00:01  0% |                                | 20kB 641kB/s eta 0:00:24
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7/site-packages/numpy-1.18.5.dist-info'
Consider using the `--user` option or check the permissions.

You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' comm

In [2]:
ls

Python Loops Exercises.ipynb  Untitled1.ipynb
Untitled.ipynb                exercise.py


In [3]:
ls

Python Loops Exercises.ipynb  exercise.ipynb
Untitled1.ipynb               exercise.py


In [4]:
import numpy as np

In [5]:
mi_arr = np.array([1,2,3,4,5,6,7])

In [6]:
mi_arr

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
type(mi_arr)

numpy.ndarray

In [9]:
for x in mi_arr:
    print(x**2)

1
4
9
16
25
36
49


In [10]:
my_list = [1,2,3,4,"wassup"]

In [11]:
my_arr2 = np.array(my_list)

In [12]:
my_arr2

array(['1', '2', '3', '4', 'wassup'], dtype='<U21')

In [13]:
print(type(my_arr2))

<class 'numpy.ndarray'>


In [16]:
my_arr2 == my_list

array([ True,  True,  True,  True,  True])

In [18]:
a_list = [1,2,3,4]

list_times_three = []

for elem in a_list:
    list_times_three.append(elem + 3)
    
print(list_times_three)

[4, 5, 6, 7]


In [20]:
a_list = [1,2,3,4,5,6]

a = np.array(a_list)
a_mas_tres = a + 3
print(a_mas_tres)


[4 5 6 7 8 9]


In [22]:
ejemplo = np.array([1,2,3,4,5])

In [24]:
ejemplo * 10

array([10, 20, 30, 40, 50])

In [25]:
a = np.array([1,2,3,4,5])
b = np.array([7,82,83,341,15])

a + b

array([  8,  84,  86, 345,  20])

In [26]:
test_1 = np.array([92,94,88,91,87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])
test_3_fixed = test_3 + 2 

In [35]:
total_grade = test_1 + test_2 + test_3_fixed

In [36]:
total_grade

array([260, 281, 248, 276, 272])

In [37]:
final_grade = total_grade / 3

In [38]:
final_grade


array([86.66666667, 93.66666667, 82.66666667, 92.        , 90.66666667])

In [44]:
text = np.array([])

for elem in final_grade:
    np.append([f"hola {elem}"])

TypeError: _append_dispatcher() missing 1 required positional argument: 'values'