In [1]:
a = np.array[5,7,8,9,9,4]

NameError: name 'np' is not defined

In [2]:
import numpy as np


In [4]:
a = np.array([5,7,8,9,9,4])



In [5]:
a[:3]

array([5, 7, 8])

In [6]:
a[-3:]

array([9, 9, 4])

In [9]:
a[::2]

array([5, 8, 9])

In [17]:
# Array 2-dimensional
## a[fila, columna]
## a[fila_inicio:fila_final, columna_inicio:columna_final]

## Ejes
## Eje 0 (axis 0) comparten misma posicion de indice (o sea la columna)
## Eje 1 (axis 1) comparten mismo array (o sea )

In [26]:
array_dos_dim = np.array([
    [1,2,3,4],
    [5,6,7,8],
])

In [27]:
array_dos_dim[0, 1]

2

In [28]:
array_dos_dim[0, :]

array([1, 2, 3, 4])

In [29]:
array_dos_dim[0, :3]

array([1, 2, 3])

In [30]:
array_dos_dim[:, 3]

array([4, 8])

In [32]:
student_scores = np.array([
    [92,94,88,91,87],
    [79,100,86,93,91],
    [87,85,72,90,92]
])

In [41]:
tanya_test_3 = student_scores[2,0]

In [42]:
print(tanya_test_3)

87


In [53]:
student_scores[0][1:]

array([94, 88, 91, 87])

In [35]:
cody_test_scores = student_scores[:, 4]

In [36]:
print(cody_test_scores)

[87 91 92]


In [48]:
student_scores_2 = [[92,94,88,91,87], [79,100,86,93,91],[87,85,72,90,92]]

In [51]:
student_scores_2[0][:]

[92, 94, 88, 91, 87]

In [54]:
a = np.array([5,7,8,9,9,4])


In [55]:
a > 5

array([False,  True,  True,  True,  True, False])

In [71]:
a[ a > 5]

array([7, 8, 9, 9])

In [57]:
x = a[ a > 5]

In [58]:
x

array([7, 8, 9, 9])

In [64]:
a[ (a < 8) | (a > 9)]

array([5, 7, 4])

In [69]:
a[ a > 9]

array([], dtype=int64)

In [72]:
my_arr = a[ a > 5]

In [73]:
my_arr
    

array([7, 8, 9, 9])

In [76]:
my_arr[ my_arr != 7]

array([8, 9, 9])

In [78]:
csv_array = np.genfromtxt('untitled.csv', delimiter=',')

In [79]:
csv_array


array([34., 55.,  6., 77., 88.])

In [80]:
np.mean(a)

7.0

In [81]:
csv_array


array([34., 55.,  6., 77., 88.])

In [94]:
##Mean

respuestas_encuesta = [5,10,3.34,4,5,6,7,8]

encuesta_array = np.array(respuestas_encuesta)

In [95]:
np.mean(encuesta_array)

6.0425

In [96]:
list_a = [1,2,3,4]


In [97]:
num = 1.234

In [98]:
round(num, 2)

1.23

In [99]:
np.round(encuesta_array)

array([ 5., 10.,  3.,  4.,  5.,  6.,  7.,  8.])

In [101]:
encuesta_array[encuesta_array > 5]

array([10.,  6.,  7.,  8.])

In [103]:
np.mean(encuesta_array > 5)

0.5

In [104]:
cantidad_cestas = np.array([
    [1,0,0],
    [0,0,1],
    [1,0,1]
    
])

In [105]:
np.mean(cantidad_cestas)

0.4444444444444444

In [108]:
np.mean(cantidad_cestas, axis=1)

array([0.33333333, 0.33333333, 0.66666667])

In [109]:
np.mean(cantidad_cestas, axis=0)

array([0.66666667, 0.        , 0.66666667])